Transform: AWS::Serverless-2016-10-31
Resources:
  AIReconRecv:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: AIReconRecv
      FunctionName: sqs-airecon-receiver
      CodeUri: src/sqs
      Handler: sqs-airecon-receiver.lambda_handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          QUEUE_NAME: !GetAtt AIReconRecvQueue.QueueName
          QUEUE_ARN: !GetAtt AIReconRecvQueue.Arn
          QUEUE_URL: !Ref AIReconRecvQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AIReconRecvQueue.QueueName
      Events:
        AIReconApiPUTairecon:
          Type: Api
          Properties:
            Path: /airecon
            Method: PUT
            RestApiId: !Ref AIReconApi

  AIReconRecvLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AIReconRecv}
  AIReconRecvQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AIReconRecvQueue
      MessageRetentionPeriod: 345600
  AIReconApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: AIReconApi
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /airecon:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AIReconRecv.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  AIReconAIMLProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AIReconAIMLProcessor
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: AIReconAIMLProcessor
      CodeUri: src/sqs
      Handler: sqs-aiml-processor.lambda_handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        AIReconRecvQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt AIReconRecvQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          QUEUE_NAME: !GetAtt AIReconPostProcessReceiver.QueueName
          QUEUE_ARN: !GetAtt AIReconPostProcessReceiver.Arn
          QUEUE_URL: !Ref AIReconPostProcessReceiver
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AIReconPostProcessReceiver.QueueName
        - AmazonAPIGatewayInvokeFullAccess
  AIReconAIMLProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AIReconAIMLProcessor}
  AIReconPostProcessReceiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AIReconPostProcessReceiver
      MessageRetentionPeriod: 345600
  AIReconPostProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sqs-aiml-post-processor
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: AIReconPostProcessor
      CodeUri: src/sqs
      Handler: sqs-aiml-post-processor.lambda_handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        AIReconPostProcessReceiver:
          Type: SQS
          Properties:
            Queue: !GetAtt AIReconPostProcessReceiver.Arn
            BatchSize: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref mfjmddaireconresults
          BUCKET_ARN: !GetAtt mfjmddaireconresults.Arn
          TABLE_NAME: !Ref mddaireconresults
          TABLE_ARN: !GetAtt mddaireconresults.Arn
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref mfjmddaireconresults
        - DynamoDBCrudPolicy:
            TableName: !Ref mddaireconresults
  AIReconPostProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AIReconPostProcessor}
  mfjmddaireconresults:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-mfjmddair-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  mfjmddaireconresultsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref mfjmddaireconresults
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt mfjmddaireconresults.Arn
              - !Sub ${mfjmddaireconresults.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  mddaireconresults:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  MessageSender:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: MessageSender
      CodeUri: src/sqs
      FunctionName: sqs-bulk-msg-sender
      Handler: sqs-bulk-msg-sender.lambda_handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          API_URL: !Sub https://${AIReconApi}.execute-api.${AWS::Region}.amazonaws.com/${AIReconApi.Stage}
  MessageSenderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MessageSender}
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: AIML PostProcessing
      Members:
        - mfjmddaireconresults
        - mddaireconresults
        - AIReconPostProcessor
    Group2:
      Label: AIML Processing
      Members:
        - AIReconAIMLProcessor
        - AIReconPostProcessReceiver
    Group3:
      Label: MSGReceiverGroup
      Members:
        - AIReconApi
        - AIReconRecv
        - AIReconRecvQueue